routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('get-word', [App\Http\Controllers\GameController::class, 'getWord']);
Route::post('check-answer', [App\Http\Controllers\GameController::class, 'checkAnswer']);
Route::get('admin', [App\Http\Controllers\AdminController::class, 'index']);
Route::get('get-detail/{user_id}', [App\Http\Controllers\AdminController::class, 'getDetail']);

Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function words()
    {
        return $this->hasMany('App\Models\Word', 'category_id', 'id');
    }
}

app/Models/History.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    protected $fillable = ['user_id', 'word_id', 'point'];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function word()
    {
        return $this->belongsTo('App\Models\Word', 'word_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = ['name', 'email', 'password', 'is_admin', 'point', 'words'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin'          => 'boolean'
    ];

    public function scopeisAdmin($query)
    {
        return $query->where('is_admin', 1);
    }

    public function scopeisUser($query)
    {
        return $query->where('is_admin', 0);
    }

    public function histories()
    {
        return $this->hasMany('App\Models\History', 'user_id', 'id');
    }

    public function getWordsCountAttribute()
    {
        $array = explode(',', $this->words);

        return count($array) - 1;
    }
}

app/Models/Word.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Word extends Model
{
    protected $fillable = ['word', 'category_id'];

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id');
    }

    public function getWordShuffledAttribute()
    {
        return str_shuffle($this->word);
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\History;
use DB;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        if (auth()->user()->is_admin == false) {
            auth()->logout();

            return redirect('/');
        }
        $sub = User::where('users.is_admin',0)->select(DB::raw("users.id,users.name,users.email,users.`point`,
                            (SELECT created_at FROM histories where user_id =users.id order by created_at desc limit 1) last_played"));
        $histories = DB::table(DB::raw("({$sub->toSql()}) as sub"))
                            ->mergeBindings($sub->getQuery())
                            ->whereNotNull('sub.last_played')
                            ->paginate(25);
        return view('admin')->with('histories', $histories);
    }

    public function getDetail($user_id)
    {
        try {
            if (auth()->user()->is_admin == false) {
                auth()->logout();
    
                return redirect('/');
            }
            $histories = DB::select("SELECT a.user_id,w.word,case when a.`point` < 0 then 'Wrong' else 'Correct' end as answer,a.`point`,a.created_at
                                    FROM histories a 
                                    LEFT JOIN words w on a.word_id =w.id 
                                    WHERE a.user_id =3
                                    ORDER BY a.created_at asc");
            foreach($histories as $key => $value){
                $data[$key]['user_id'] = $value->user_id;
                $data[$key]['word'] = $value->word;
                $data[$key]['answer'] = $value->answer;
                $data[$key]['point'] = $value->point;
                $data[$key]['play_time'] = \Carbon\Carbon::parse($value->created_at)->diffForHumans();
            }
            $response = [
                'code'      => 200,
                'message'   => 'Success',
                'data'      => $data
            ];
        } catch (\Exception $e) {
            $msg['file'] = $e->getFile();
            $msg['message'] = $e->getMessage();
            $msg['line'] = $e->getLine();
            \Log::error($msg);
            $response = [
                'code'      => 400,
                'message'   => 'Internal Server Error'
            ];
        }
        return response()->json($response);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Word;
use App\Models\History;
use Illuminate\Http\Request;

class GameController extends Controller
{
    public function index()
    {
        return view('main');
    }

    public function getWord()
    {
        $wordIds = ! empty(auth()->user()->words) ? explode(',', auth()->user()->words) : '';
        $word = Word::with('category')
                    ->when(! empty($wordIds), function ($query) use ($wordIds) {
                        return $query->whereNotIn('id', $wordIds);
                    })
                    ->when(config('database.default') == 'mysql', function ($query) {
                        return $query->orderByRaw('RAND()');
                    })
                    ->first();
        $response = [
            'id'       => $word->id,
            'word'     => $word->word_shuffled,
            'category' => $word->category->name
        ];

        return response()->json($response);
    }

    public function checkAnswer(Request $request)
    {
        $wordId = $request->word_id;
        $answer = $request->answer;

        $words = Word::find($wordId);
        $user  = auth()->user();

        // Check answer
        if ($words->word == $answer) {
            $result = ['status' => 'correct', 'point' => 10];

            // Update score & word
            $user->point += $result['point'];
            $user->words = ltrim($user->words.','.$words->id, ',');
        } else {
            $result = ['status' => 'wrong', 'point' => -5];

            // update only score
            $user->point += $result['point'];
        }
        $user->save();

        // Write history
        History::create([
            'user_id' => auth()->user()->id,
            'word_id' => $words->id,
            'point'   => $result['point']
        ]);

        return response()->json($result);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (auth()->user()->is_admin) {
            return redirect('admin');
        }
        return view('home');
    }
}

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-12">
        {{-- <div class="box-table">
            <table>
                <tr>
                    <th>Name</th>
                    <th>Points</th>
                    <th>Played</th>
                </tr>
                @forelse($histories as $history)
                <tr>
                    <td>{{ $history->user->name }}</td>
                    <td class="text-center">{{ $history->point > 0 ? '+'.$history->point : $history->point }}</td>
                    <td class="text-center">{{ $history->created_at->diffForHumans() }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="3">no data available</td>
                </tr>
                @endforelse
            </table>
            {{ $histories->links() }}
        </div> --}}
        <table class="table table-striped">
            <thead style="background: #dddd">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Points</th>
                    <th>Last Played</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse($histories as $history)
                <tr>
                    <td>{{ $history->name }}</td>
                    <td>{{ $history->email }}</td>
                    <td >{{ $history->point}}</td>
                    <td >{{ \Carbon\Carbon::parse($history->last_played)->diffForHumans() }}</td>
                    <td ><i class="far fa-eye" onclick="detail({{$history->id}})" style="font-size: 25px;" data-toggle="tooltip" data-placement="right" title="Detail"></i></td>
                </tr>
                @empty
                <tr>
                    <td colspan="3">no data available</td>
                </tr>
                @endforelse
            </tbody>
        </table>
        {{ $histories->links() }}
    </div>
    {{-- MODAL --}}
    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Play History</h5>
            </div>
            <div class="modal-body">
                <table id="table" class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Word</th>
                            <th scope="col">Answer Result</th>
                            <th scope="col">Accumulated Points</th>
                            <th scope="col">Play Time</th>
                          </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function detail(user_id){
            $.ajax({
                method: 'GET',
                url: `get-detail/${user_id}`
            }).done(function(result) {
                if(result['code']==200){
                    $('#table > tbody').empty()
                    if(result['data'].length > 0){
                        var point = 0;
                        for (let index = 0; index < result['data'].length; index++) {
                            var no = index+1;
                            point = point + parseInt(result['data'][index]['point'])
                            table = "<tr>"+
                                        " <th scope='row'>"+no+"</th>"+
                                        " <td>"+result['data'][index]['word']+"</td>"+
                                        " <td>"+result['data'][index]['answer']+"</td>"+
                                        " <td>"+point+"</td>"+
                                        " <td>"+result['data'][index]['play_time']+"</td>"+
                                    " </tr>"
                            $('#table > tbody').append(table);
                        }
                        $('.modal').modal('show');
                    }else{
                        alert('Oopss no data play histori')
                    }
                }
            });
        }
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="header">
                        <div class="box-score" style="float: left;">
                            <label>SCORE</label>
                            <span id="score">{{ auth()->user()->point ?? 0 }}</span>
                        </div>    
                        <div class="box-score" style="float: left;margin-left: 15px;">
                            <label>WORDS</label>
                            <span id="word_number">{{ auth()->user()->words_count ?? 0 }}</span>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="box-category">
                        <span>Topic</span>
                    </div>
                </div>
                <div class="box-answer">
                    <div class="answer-wrapper">
                        <div class="outline">
                            <span class="notification correct hidden">correct +10</span>
                            <div class="answer"></div>
                        </div>
                    </div>
                </div>
                <div class="box-button">
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(function() {
        var answer = '';
        var word_id = 0;
        var score = {{ auth()->user()->point ?? 0 }};
        var word_number = {{ auth()->user()->words_count ?? 0 }};

        function erase() {
            answer = '';
            $('.answer').empty();
            $('.box-button button').prop('disabled', false);
            $('.notification').hide();
        }

        function buildButton(word) {
            $('.box-button').empty();

            for(i = 0; i < word.length; i++) {
                $('.box-button').append('<button type="button"><span style="font-size:30px">' + word[i] + '</span></button>');

                if (i == 2 || i == 5) {
                    $('.box-button').append('<br>');
                }
            }

            $('.box-button').append('<button type="button" class="btn-erase"><span style="font-size:30px"><i class="fas fa-eraser"></i></span></button>');
        }

        function getWord() {
            $.ajax({
                method: 'GET',
                url: 'get-word'
            }).done(function(data) {
                erase();
                buildButton(data.word);

                word_id = data.id;

                $('.box-category span').html(data.category);

                $('.box-button button').bind('click', function() {
                    $(this).prop('disabled', true);
                    $('.answer').append('<button class="btn-small"><span>' + $(this).children().html() + '</span></button>');

                    answer += $(this).children().html();

                    if (answer.length == data.word.length) {
                        $('.btn-erase').prop('disabled', true);

                        checkAnswer(word_id, answer);
                    }
                });

                $('.btn-erase').bind('click', function() {
                    erase();
                });
            });
        }

        function checkAnswer(id, data) {
            $.ajax({
                method: 'POST',
                url: 'check-answer',
                data: {'_token'  : $('meta[name="csrf-token"]').attr('content'),'word_id': id, 'answer': data},
            }).done(function(data) {
                if (data.status == 'correct') {
                    score += data.point;
                    $("#score").html(score);
                    word_number++;
                    $("#word_number").html(word_number);

                    $('.notification').removeClass('wrong').addClass('correct').html(data.status + ' +' + data.point).fadeIn(1000).fadeOut(3000);
                    setTimeout(function() {
                        getWord();
                        $('.btn-erase').prop('disabled', false);
                    }, 3000);
                } else if (data.status == 'wrong') {
                    score += data.point;
                    $("#score").html(score);

                    $('.notification').removeClass('correct').addClass('wrong').html(data.status + ' ' + data.point).fadeIn(1000).fadeOut(3000);
                $('.btn-erase').prop('disabled', false);
                }
            });
        }

        getWord();
    });
</script>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/game.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>